version: 0.0
os: linux
files:
  - source: /
    destination: /opt/cicd-test
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 4755
hooks:
  ApplicationStart:
    - location: _scripts/start-test.sh
      timeout: 180
      runas: ec2-user
