version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "======================  codebuild cicd hello test   ============================="
  build:
    commands:
    - npm install

artifacts:
  base-directory: ./cicd-test
  files:
    - '**/*'

