version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing"
      - npm install
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - npm run start
  post_build:
    commands:
      - echo "post_build"
artifacts:
  files:
    - '**/*'
    - location
  base-directory: dist
  discard-paths: no 
