version: 0.2
env: 
  variables:
    LAMBDA_NAME: alfred-1013-lambda-test
    ALIAS: lastest
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yum update -y
      - yum install zip -y
      - yum install jq -y
      - mkdir -p dist
  build:
    commands:
      - zip -r lambda.zip lambda/*
  post_build:
    commands:
      - echo $LAMBDA_NAME
      # - CURRENT_VERSION = $(aws lambda get-alias --function-name $LAMBDA_NAME --name $ALIAS | jq -r .FunctionVersion)
      - echo CURRENT_VERSION
      - aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://lambda.zip
      # - TARGET_VERSION = $(aws lambda publish-version --function-name $LAMBDA_NAME | jq -r .Version)
      # - echo TargetVersion
      # - sed -i "s/ReplaceCurrentVersion/$CURRENT_VERSION" appspec.yml
      # - sed -i "s/ReplaceTargetVersion/$TargetVersion" appspec.yml
      - cp appsepc.yml dist/appapec.yml
artifacts:
  files:
    - 'appspec.yml'
  base-directory: dist
  discard-paths: no 
  
